---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: "ci: "
    groups:
      all-actions:
        patterns:
          - "*" # This groups all GitHub Action updates into one PR
