# SPDX-License-Identifier: MIT
---
ignore: |
  /.tox/
extends: default
rules:
  braces:
    max-spaces-inside: 1
    level: error
  brackets:
    max-spaces-inside: 1
    level: error
  truthy:
    allowed-values: ["yes", "no", "true", "false"]
    level: error
  document-start: disable
