# SPDX-License-Identifier: MIT
---
extends: yamllint_defaults.yml
# possible customizations over the base yamllint config
# skip the yaml files in the /tests/ directory
# NOTE: If you want to customize `ignore` you'll have to
# copy in all of the config from .yamllint.yml, then
# add your own - so if you want to just add /tests/ to
# be ignored, you'll have to add the ignores from the base
# ignore: |
#   /tests/
#   /.tox/
# skip checking line length
# NOTE: the above does not apply to `rules` - you do not
# have to copy all of the rules from the base config
# rules:
#   line-length: disable
rules:
  truthy: disable
  line-length:
    ignore: |
      /tests/tasks/setup_mock_wifi_wpa3_owe.yml
      /tests/tasks/setup_mock_wifi_wpa3_sae.yml
      /tests/tests_ethtool_coalesce_initscripts.yml
      /tests/tests_ethtool_ring_initscripts.yml
      /tests/tests_team_plugin_installation_nm.yml
      /tests/tests_wireless_plugin_installation_nm.yml
      /tests/tests_wireless_wpa3_owe_nm.yml
      /tests/tasks/setup_mock_wifi_wpa3_owe.yml
      /tests/tests_auto_gateway_initscripts.yml
      /tests/tests_bond_deprecated_initscripts.yml
      /tests/tests_ethtool_features_initscripts.yml
      /tests/tests_wireless_wpa3_sae_nm.yml
