# SPDX-License-Identifier: MIT
---
extends: default
ignore: |
  /.tox/
  tests/roles/
rules:
  line-length:
    ignore: '/tests/tasks/setup_mock_wifi_wpa3_owe.yml

      /tests/tasks/setup_mock_wifi_wpa3_sae.yml

      /tests/tests_ethtool_coalesce_initscripts.yml

      /tests/tests_ethtool_ring_initscripts.yml

      /tests/tests_route_device_initscripts.yml

      /tests/tests_team_plugin_installation_nm.yml

      /tests/tests_wireless_plugin_installation_nm.yml

      /tests/tests_wireless_wpa3_owe_nm.yml

      /tests/tasks/setup_mock_wifi_wpa3_owe.yml

      /tests/tests_auto_gateway_initscripts.yml

      /tests/tests_bond_deprecated_initscripts.yml

      /tests/tests_ethtool_features_initscripts.yml

      /tests/tests_wireless_wpa3_sae_nm.yml

      /tests/tests_eth_pci_address_match_nm.yml

      /tests/playbooks/tests_eth_pci_address_match.yml

      /tests/tasks/setup_802_1x_server.yml

      /tests/tests_bond_removal_initscripts.yml

      /tests/tests_bond_cloned_mac_initscripts.yml

      /tests/tests_bridge_cloned_mac_initscripts.yml

      /tests/tests_bridge_cloned_mac_nm.yml

      '
