# SPDX-License-Identifier: BSD-3-Clause
---
- name: Ensure ansible_facts used by role are present
  setup:
    gather_subset: "{{ __network_required_facts_subsets }}"
  when: __network_required_facts |
    difference(ansible_facts.keys() | list) | length > 0
  no_log: true

- name: Determine if system is ostree and set flag
  when: not __network_is_ostree is defined
  block:
    - name: Check if system is ostree
      stat:
        path: /run/ostree-booted
      register: __ostree_booted_stat

    - name: Set flag to indicate system is ostree
      set_fact:
        __network_is_ostree: "{{ __ostree_booted_stat.stat.exists }}"

- name: Determine if system is booted with systemd
  when: __network_is_booted is not defined
  block:
    - name: Run systemctl
      # noqa command-instead-of-module
      command: systemctl is-system-running
      register: __is_system_running
      changed_when: false
      check_mode: false
      failed_when: false

    - name: Require installed systemd
      fail:
        msg: "Error: This role requires systemd to be installed."
      when: '"No such file or directory" in __is_system_running.msg | d("")'

    - name: Set flag to indicate that systemd runtime operations are available
      set_fact:
        # see https://www.man7.org/linux/man-pages/man1/systemctl.1.html#:~:text=is-system-running%20output
        __network_is_booted: "{{ __is_system_running.stdout != 'offline' }}"

- name: Check which services are running
  service_facts:
  no_log: true

# needed for ansible_facts.packages
- name: Check which packages are installed
  package_facts:
  no_log: true
