# SPDX-License-Identifier: MIT
---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  enabled: false
platforms:
  - name: centos-6
    image: registry.centos.org/centos:6
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    command: /sbin/init
  - name: centos-7
    image: registry.centos.org/centos/systemd:latest
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    command: /usr/lib/systemd/systemd --system
  - name: centos-8
    image: registry.centos.org/centos:8
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    command: /usr/lib/systemd/systemd --system
    groups:
      - py3
provisioner:
  name: ansible
  log: true
  lint:
    enabled: false
  playbooks:
    converge: ../../tests/tests_default.yml
  inventory:
    group_vars:
      py3:
        ansible_python_interpreter: /usr/bin/python3
scenario:
  name: default
  test_sequence:
    - destroy
    - create
    - converge
    - idempotence
    - check
    - destroy
