# SPDX-License-Identifier: BSD-3-Clause
---
- hosts: all
  tasks:
    - include_role:
        name: linux-system-roles.network
      vars:
        network_connections:
          - name: "{{ network_interface_name1 }}"
            state: up
            type: ethernet
            ip:
              dhcp4: "no"
              auto6: "no"
            ethtool:
              features:
                gro: "no"
                gso: "yes"
                tx_sctp_segmentation: "no"
