#!/bin/bash

set -ex

SCRIPTDIR=$(dirname $0)
CONFIG=${SCRIPTDIR}/config.sh

if [[ -f ${CONFIG} ]]; then
  . ${CONFIG}
fi

if [[ "${LSR_EXTRA_PACKAGES}" ]]; then
  sudo apt-get update
  sudo apt-get install -y ${LSR_EXTRA_PACKAGES}
fi
