#!/bin/bash

set -ex

SCRIPTDIR=$(dirname $0)
CONFIG=${SCRIPTDIR}/config.sh

if [[ -f ${CONFIG} ]]; then
  . ${CONFIG}
fi

tox "$@"
if [[ "x${LSR_MSCENARIOS}" != "x" ]]; then
  for X in ${LSR_MSCENARIOS}; do
    LSR_MSCENARIO=${X} tox -e molecule_lint
    LSR_MSCENARIO=${X} tox -e molecule_syntax
    LSR_MSCENARIO=${X} tox -e molecule_test
  done
fi
