# Codespell configuration is within .codespellrc
---
name: Codespell
on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      requested:
        description: Run this workflow for an authorized /citest command
        required: true
        type: boolean
permissions:
  contents: read
  pull-requests: read
  # This is required for the ability to create/update the Pull request status
  statuses: write
jobs:
  codespell:
    if: inputs.requested || github.event_name != 'issue_comment'
    name: Check for spelling errors
    runs-on: ubuntu-latest
    steps:
      - name: Get PR head SHA and context
        if: github.event_name == 'issue_comment'
        id: head_sha_context
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.issue.number }}
          CONTEXT: "${{ github.workflow }} / Check for spelling errors (pull_request)"
        run: |
          set -euxo pipefail
          head_sha=$(gh api "repos/$REPO/pulls/$PR_NUMBER" --jq '.head.sha')
          echo "head_sha=$head_sha" >> "$GITHUB_OUTPUT"
          echo "context=$CONTEXT" >> "$GITHUB_OUTPUT"

      - name: Set commit status as pending
        if: github.event_name == 'issue_comment'
        uses: myrotvorets/set-commit-status-action@c0f880c99d91381c6fdb97726f03feb8004409b4  # master
        with:
          sha: ${{ steps.head_sha_context.outputs.head_sha }}
          status: pending
          context: ${{ steps.head_sha_context.outputs.context }}
          description: Test started
          targetUrl: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/job/${{ job.check_run_id }}

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false
          ref: ${{ steps.head_sha_context.outputs.head_sha || github.sha }}

      - name: Codespell
        uses: codespell-project/actions-codespell@8f01853be192eb0f849a5c7d721450e7a467c579  # v2.2

      - name: Set final commit status
        if: always() && github.event_name == 'issue_comment' && steps.head_sha_context.outputs.head_sha != ''
        uses: myrotvorets/set-commit-status-action@c0f880c99d91381c6fdb97726f03feb8004409b4  # master
        with:
          sha: ${{ steps.head_sha_context.outputs.head_sha }}
          status: ${{ job.status }}
          context: ${{ steps.head_sha_context.outputs.context }}
          description: Test finished
          targetUrl: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/job/${{ job.check_run_id }}
