name: integration

on:
  pull_request:
    types: [opened, synchronize, reopened]
  merge_group:
    branches:
      - main
    types:
      - checks_requested
  push:
    branches:
      - main

jobs:
  integration:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: "c7"
          - os: "c8s"
          - os: "c9s"

    steps:
      - uses: actions/checkout@v3

      - name: Run tests
        run: sudo .github/run_test.sh --os ${{ matrix.os }}
