---
# yamllint disable rule:line-length
name: Markdown Lint
on:  # yamllint disable-line rule:truthy
  pull_request:
  merge_group:
    branches:
      - main
    types:
      - checks_requested
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: read
jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - name: Update pip, git
        run: |
          set -euxo pipefail
          sudo apt update
          sudo apt install -y git

      - name: Check out code
        uses: actions/checkout@v3

      # CHANGELOG.md is generated automatically from PR titles and descriptions
      # It might have issues but they are not critical
      - name: Lint all markdown files except for CHANGELOG.md
        uses: docker://avtodev/markdown-lint:master
        with:
          args: >-
            --ignore=CHANGELOG.md
            **/*.md
          config: .markdownlint.yaml
