name: PR Title Lint
on:  # yamllint disable-line rule:truthy
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited
  merge_group:
    branches:
      - main
    types:
      - checks_requested
permissions:
  contents: read
jobs:
  commit-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install conventional-commit linter
        run: npm install @commitlint/config-conventional @commitlint/cli

      - name: Run commitlint on PR title
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        # Echo from env variable to avoid bash errors with extra characters
        run: echo "$PR_TITLE" | npx commitlint --verbose
