---
name: PR Title Lint
on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      requested:
        description: Run this workflow for an authorized /citest command
        required: true
        type: boolean
      pr_title:
        description: Pull request title to validate
        required: true
        type: string
permissions:
  contents: read
  pull-requests: read
jobs:
  commit-checks:
    if: inputs.requested || github.event_name != 'issue_comment'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Install pr_title_lint.py
        run: curl -o pr_title_lint.py https://raw.githubusercontent.com/linux-system-roles/auto-maintenance/main/pr_title_lint.py

      - name: Run pr_title_lint.py on PR title
        env:
          PR_TITLE: ${{ inputs.pr_title || github.event.pull_request.title }}
        # Echo from env variable to avoid bash errors with extra characters
        run: python3 pr_title_lint.py "${PR_TITLE}"
