---
# yamllint disable rule:line-length
name: Woke
on:  # yamllint disable-line rule:truthy
  - pull_request
permissions:
  contents: read
jobs:
  woke:
    if: |
      !(github.event_name == 'pull_request' && contains(github.event.pull_request.title, '[citest_skip]'))
    name: Detect non-inclusive language
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false

      - name: Run lsr-woke-action
        # Originally, uses: get-woke/woke-action@v0
        uses: linux-system-roles/lsr-woke-action@33e72e28c826f05aaee08d0b70c7d2cd9e0a39a7  # main
        with:
          woke-args: "-c https://raw.githubusercontent.com/linux-system-roles/tox-lsr/main/src/tox_lsr/config_files/woke.yml --count-only-error-for-failure"
          # Cause the check to fail on any broke rules
          fail-on-error: true
